### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by FlappyDev-ctrl** [AStrangePotato/Tetr.io-Bot#1]
Hello I managed to launch your bot unfortunately all the parts are put to the left a little randomly I tried to change the delay it still doesn't work an idea?

![image](https://github.com/user-attachments/assets/dc30be18-0e12-47da-9794-9416da6d313b)

**Comment by danielyx-z** [comment]
What resolution is your monitor? I haven't created a dynamic solution yet to find the region's for each piece it needs to look at so it is hardcoded for 2560x1440 for now.

**Comment by FlappyDev-ctrl** [comment]
1920*1080 :D

**Comment by AStrangePotato** [comment]
I will create a new commit with an option for 1980x1080 later today then.

**Comment by danielyx-z** [comment]
It should be fixed. Just change the flag in detect.py to your resolution and it should work regardless of what your system scaling % is at.
